//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandingPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string malla { get; set; }
        public bool estado { get; set; }
        public int idSubSeccion { get; set; }
    
        public virtual SubSeccion SubSeccion { get; set; }
    }
}
