//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandingPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string celular { get; set; }
        public string mensaje { get; set; }
        public int idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
